/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About | Hack The Winter 2023</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className="pt-36 ">
        <div className="w-2/5">
          <h1 className="text-8xl pb-16 text-[#183E43]">
            All About <br/><span className="text-[#3EB0AC]">Programming</span>
          </h1>
          <div className="text-xl   py-16  tracking-wide">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. 
          </div>
          <div className="flex pt-16 justify-between">
            <div className=" w-1/3 text-2xl text-center rounded-full border-2 border-[#F9E596] bg-[#F9E596] py-6 px-12 cursor-pointer hover:bg-transparent ">Register</div>
            <div className=" w-1/3 text-2xl py-6 px-12 text-center rounded-full border-2 border-[#F9E596] cursor-pointer hover:bg-[#F9E596] ">Learn More</div>
          </div>
        </div>
        
        <img src='./assets/homepage-bg/Ellipse16.png' alt="Ellipse16" className='absolute top-12 right-24 ' width={750} />
        <img src='./assets/homepage-bg/Ellipse13.png' alt="Ellipse13" className='absolute top-0 right-0' width={700} />
        <img src='./assets/homepage-bg/Ellipse14.png' alt="Ellipse14" className='absolute top-[39vh] right-96' width={600} />
        <img src='./assets/homepage-bg/Ellipse15.png' alt="Ellipse15" className='absolute top-0 right-0' width={600} />

      </div>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
